Repository camotio02/app_receitas, pull requests merged in 2023-08, with the labels that each got.

#33 corrige forma de fazer as buscas
  src/pages/MainLayout/search/index.jsx
Labels: bug

#38 Limitthelevelofcomponentization
  firebase-messaging-sw.js
  firebase.config.js
  package-lock.json
  package.json
  src/App.jsx
  src/api/recipes/recipes.js
  src/api/users/notifications.js
  src/api/users/users.js
  src/componentes/AppBar/content/index.jsx
  src/componentes/AppBar/index.jsx
  src/pages/MainLayout/components/UserMenu/index.jsx
  src/pages/RECIPES/CreateRecipes/RecipeForm.jsx
  src/pages/RECIPES/CreateRecipes/componentes/createRecipeHeader/index.jsx
  src/pages/RECIPES/CreateRecipes/componentes/createRecipesAddSteps/index.jsx
  src/pages/RECIPES/CreateRecipes/createRecipe.jsx
  src/pages/RECIPES/FavoriteRecipes/componentes/body/index.jsx
  src/pages/RECIPES/FavoriteRecipes/componentes/cardFavoriteRecipe/index.jsx
  src/pages/RECIPES/FavoriteRecipes/componentes/header/index.jsx
  src/pages/RECIPES/MyRecipes/componentes/AppBar/index.jsx
  src/pages/RECIPES/MyRecipes/index.jsx
  src/pages/RECIPES/ReviewRecipes/componentes/APPBAR/index.jsx
  src/pages/RECIPES/ReviewRecipes/index.jsx
  src/pages/RECIPES/recipeOpenNotifi/index.js
  src/pages/RECIPES/recipeOpenNotifi/index.jsx
  src/pages/USERS/USERFILES/EDITUSERPAGE/componentes/cardMedia/index.jsx
  src/pages/USERS/USERFILES/EDITUSERPAGE/index.jsx
  src/pages/USERS/notifications/index.jsx
  src/pages/USERS/userOpenNot/index.js
  src/pages/USERS/userOpenNot/index.jsx
Labels: enhancement

#41 adiciona todo
  todo.md
Labels: documentation

#40 Comment
  package-lock.json
  src/api/usersComments/index.js
  src/componentes/CARDRECIPE/index.jsx
  src/componentes/textField/textField.jsx
  src/pages/MainLayout/components/MenuContent/index.jsx
  src/pages/MainLayout/components/MenuContent/styles.js
  src/pages/MainLayout/consts/links.jsx
  src/pages/MainLayout/index.jsx
  src/pages/RECIPES/CreateRecipes/componentes/createRecipesMoreFields/index.jsx
  src/pages/RECIPES/CreateRecipes/createRecipe.jsx
  src/pages/RECIPES/CreateRecipes/validation.js
  src/pages/RECIPES/DetailsRecipes/componentes/CardMidiaDetailsRecipes/index.jsx
  src/pages/RECIPES/DetailsRecipes/componentes/CardMidiaDetailsRecipes/styles.js
  src/pages/RECIPES/DetailsRecipes/componentes/comments/index.jsx
  src/pages/RECIPES/DetailsRecipes/componentes/comments/styles.js
  src/pages/RECIPES/DetailsRecipes/componentes/message/index.jsx
  src/pages/RECIPES/DetailsRecipes/index.jsx
  src/pages/RECIPES/FavoriteRecipes/componentes/cardFavoriteRecipe/index.jsx
  src/pages/RECIPES/FavoriteRecipes/componentes/header/index.jsx
  src/pages/RECIPES/ReviewRecipes/componentes/IMAGECARDS/index.jsx
  src/pages/RECIPES/ReviewRecipes/componentes/PAGINATION/index.jsx
  src/pages/RECIPES/ReviewRecipes/index.jsx
  todo.md
Labels: enhancement
